homeassistant:
  name: OXOTH1Ks home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 60
  unit_system: metric
  time_zone: Europe/Volgograd
  customize: !include customize.yaml


# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

# Enables configuration UI
config:

#https://home-assistant.io/components/logger/
logger:
  default: error

#lovelace:
#  mode: yaml

http:
  api_password: !secret http_password
  base_url: !secret home_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key


updater:
  # include_used_components: true

discovery:
conversation:
history:
custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json

logbook:

map:
sun:
ios:
system_health:

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: eu-central-1
    voice: Maxim

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

binary_sensor:
  - platform: hikvision
    name: Датчик движения
    host: 192.168.1.138
    username: admin
    password: !secret camera_kitchen_switch
  - platform: "mqtt"
    name: "Water leak"
    state_topic: "zigbee2mqtt/0x00158d000240306d"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.water_leak }}"
    device_class: "moisture"


xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_key

light:
  - platform: xiaomi_miio
    name: living_room
    host: 192.168.1.198
    token: !secret light_token1
    model: philips.light.bulb
  - platform: xiaomi_miio
    name: bathroom
    host: 192.168.1.49
    token: !secret light_token2
    model: philips.light.bulb
  - platform: switch
    name: Bathroom wall
    entity_id: switch.wall_switch_158d00022ec91b

device_tracker:
  - platform: snmp
    host: 192.168.1.1
    community: !secret snmp_commynity
    baseoid: 1.3.6.1.2.1.4.22.1.2
    track_new_devices: no
    consider_home: 600
    interval_seconds: 20

switch:
  - platform: "mqtt"
    name: "ariston_wb"
    state_topic: "/devices/wb-mr6c_103/controls/K1"
    command_topic: "/devices/wb-mr6c_103/controls/K1/on"
#    availability_topic: "home/bedroom/switch1/available"
    payload_on: "1"
    payload_off: "0"
    state_on: "1"
    state_off: "0"
    optimistic: false
    qos: 0
    retain: true
  - platform: "mqtt"
    name: "wall_switch_158d00022ec91b"
    state_topic: "zigbee2mqtt/0x00158d00022ec91b"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/0x00158d00022ec91b/set"
  - platform: hikvisioncam
    host: 192.168.1.138
    name: Датчик кухня
    username: admin
    password: !secret camera_kitchen_switch
  - platform: broadlink
    host: 192.168.1.28
    mac: '78:0f:77:28:00:9e'
    timeout: 15
    switches:
      marantz_receiver:
        friendly_name: "Ресивер"
#        command_on: 'AAAAcQAAACQAIAAgACAAIAAgACAAQAAgACAAIAAgACAAIAChACAAIAAgAEAAIAAgAEAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAQAAgCqsAIAAgACAAIAAgACAAQAAgACAAIAAgACAAIAChACAAIAAgAEAAIAAgAEAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAQAAgBLA'
#        command_off: 'AAAAcQAAACIAIAAgACAAIAAgACAAQAAgACAAIAAgACAAIAChACAAIAAgAEAAIAAgAEAAIAAgACAAIAAgACAAIAAgACAAIABAAEAKqwAgACAAIAAgACAAIABAACAAIAAgACAAIAAgAKEAIAAgACAAQAAgACAAQAAgACAAIAAgACAAIAAgACAAIAAgAEAAQASw'
        command_on: 'JgCcAB4dHhweHT0bHhwfHB4dHhwfOh4cOx0eAAuuHxwfGx8bPhseHB8bHx0fGx86Hxs8HB8AC6wfHB4cHxw9Gx8bHxsgHB8bHzofGzwcHwALrB4dHhweHTwcHhweHB8dHhwfOh4cOx0eAAutHh0eHB4dPBweHB4cHx0eHB86Hhw7HR4AC60eHR4cHh08HB4cHh0eHR4dHDweHDsdHgANBQAAAAAAAAAAAAAAAA=='
        command_off: 'JgCcAB4dHhweHT0bHhwfHB4dHhwfOh4cOx0eAAuuHxwfGx8bPhseHB8bHx0fGx86Hxs8HB8AC6wfHB4cHxw9Gx8bHxsgHB8bHzofGzwcHwALrB4dHhweHTwcHhweHB8dHhwfOh4cOx0eAAutHh0eHB4dPBweHB4cHx0eHB86Hhw7HR4AC60eHR4cHh08HB4cHh0eHR4dHDweHDsdHgANBQAAAAAAAAAAAAAAAA=='

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
#  - platform: yandex
#    api_key: !secret ya_api_weather

camera:
  - platform: ffmpeg
    name: Kitchen
    ffmpeg_bin: /usr/bin/ffmpeg
    input: !secret kitchen_url
#    extra_arguments: -pred 1
  - platform: ffmpeg
    name: Door
    ffmpeg_bin: /usr/bin/ffmpeg
    input: !secret door_url
#    extra_arguments: -pred 1
  - platform: ffmpeg
    name: Dacha
    ffmpeg_bin: /usr/bin/ffmpeg
    input: !secret dacha_url
#    extra_arguments: -pred 

mqtt:
  broker: 192.168.1.101
  port: 1883
  client_id: home-assistant-2
  keepalive: 60
  username: !secret mqtt_login
  password: !secret mqtt_password
  protocol: 3.1
  birth_message:
    topic: "tele/hass2/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "tele/hass2/LWT"
    payload: "Offline"
    qos: 1
    retain: true

fan:
  - platform: xiaomi_miio
    host: 192.168.1.158
    token: !secret smartmi_token
    model: zhimi.humidifier.ca1

shopping_list:

input_number:
  internet_traffic_delta_in:
    name: "Traffic IN Delta"
    initial: 0
    min: 0
    max: 1000000000000

  internet_traffic_delta_out:
    name: "Traffic OUT Delta"
    initial: 0
    min: 0
    max: 1000000000000

climate:
  - platform: generic_thermostat
    name: Ariston
    heater: switch.ariston_wb
    target_sensor: sensor.temperature_158d00023764a1
    ac_mode: False
    min_temp: 18
    max_temp: 30
    hot_tolerance: 0.5
  - platform: broadlink
    name: Aeronik
    host: 192.168.1.28
    mac: '78:0f:77:28:00:9e'
    timeout: 15
    ircodes_ini: 'broadlink_climate_codes/aeronik.ini'
    min_temp: 16
    max_temp: 30
    target_temp: 24
    target_temp_step: 1
    temp_sensor: sensor.temperature_158d00023764a1
    default_operation: 'off'
    default_fan_mode: auto
    customize:
      operations:
        - 'off'
        - cool
        - heat
      fan_modes:
        - auto

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_secret


telegram_bot:
  - platform: polling
    proxy_url: !secret telegram_proxy_url
    proxy_params:
      username: !secret telegram_proxy_username
      password: !secret telegram_proxy_password
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_bot_chat_id
      - !secret telegram_bot_group_chat_id
      - !secret telegram_bot_chat_id_2

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_bot_chat_id
  - name: telegram_group
    platform: telegram
    chat_id: !secret telegram_bot_group_chat_id

recorder:
  purge_interval: 1
  purge_keep_days: 7
  include:
    entities:
      - binary_sensor.motion
      - binary_sensor.door_window_sensor_158d0001a9c200
      - binary_sensor.motion_sensor_158d0001b177e8
      - binary_sensor.switch_158d0001aaab2d
      - binary_sensor.water_leak
      - climate.aeronik
      - climate.ariston
      - device_tracker.iphone
      - device_tracker.iphone_2
      - fan.xiaomi_miio_device
      - group.all_devices
      - group.all_lights
      - light.bathroom
      - light.bathroom_wall
      - light.gateway_light_286c07f1c549
      - light.living_room
      - lock.polycontrol_danalock_v3_btze_locked_2
      - sensor.cpu_temperature
      - sensor.co2_kitchen
      - sensor.humidity_158d00023764a1
      - sensor.pressure_158d00023764a1
      - sensor.processor_use
      - sensor.temperature_158d00023764a1
      - sensor.water_level
      - switch.datchik_kukhnia
      - switch.ariston_wb
      - switch.marantz_receiver
      - switch.plug_158d0001b195fd

google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  exposed_domains:
    - switch
    - light
    - climate
    - media_player

zone:
  - name: Unico
    latitude: !secret unico_lat
    longitude: !secret unico_long
    radius: 100
    icon: mdi:database
  - name: Magic Smoker
    latitude: !secret ms_lat
    longitude: !secret ms_long
    radius: 100
    icon: mdi:water
  - name: Dacha
    latitude: !secret dacha_lat
    longitude: !secret dacha_long
    radius: 100
    icon: mdi:shovel
  - name: EXNails
    latitude: !secret nail_lat
    longitude: !secret nail_long
    radius: 100
    icon: mdi:emoticon-poop

apple_tv:
  - host: 192.168.1.237
    login_id: !secret appletv_login_id
    name: Apple TV
#    start_off: true
#    credentials: !secret appletv_creditnails

homekit:
  port: 51828 
  auto_start: false
  filter:
    include_domains:
      - climate
      - device_tracker
      - switch
      - binary_sensor
      - light
      - media_player
      - lock
      - sensor
      - script
    exclude_entities:
      - sensor.cpu_temperature
      - sensor.co2_kitchen
  entity_config:
    media_player.samsungtv:
      feature_list:
        - feature: on_off

media_player:
#  - platform: plex
#    entity_namespace: 'plex'
  - platform: samsungtv
    host: 192.168.1.195
    port: 8002
    mac: f8:3f:51:9c:7f:6c
    name: SamsungTV
    timeout: 5
  - platform: mpd
    host: 192.168.1.101
    password: knt9mxsd
  # - platform: vlc
  #   name: Ubuntu_speaker
  #   arguments: '-I dummy --play-and-exit --aout=pulse'

influxdb:
  host: 192.168.1.101
  port: 8086
  database: homeassistant
  username: !secret influx_user
  password: !secret influx_pass
  max_retries: 3
  default_measurement: state

